### ISSUE TITLE
zerone api 生成的 ts 文件没有使用 import type

### ISSUE THREAD

**Issue by longjuan** [zeronejs/zerone#728]
zerone api 生成的 ts 文件中对于类的导入使用了`import`，而不是`import type`
![image](https://github.com/zeronejs/zerone/assets/28662535/bab54ac6-b123-41dc-affe-a91fc4657e7d)

期望自动生成`import type`

**Comment by zlmica** [comment]
出现这个报错，有两种可能：
1.项目使用了 tsconfig.json 配置的 noImplicitAny: true, 一个没有。
当设置 noImplicitAny 时,TypeScript 会强制要求明确指定类型。而通过 import 而非 import type 导入时,默认会将类型设置为 any。所以一个项目会报错要求改为 import type。
2.项目使用了 ESLint 规则要求必须使用 import type。

可以尝试修改配置
1.修改 TypeScript 配置，修改 tsconfig.json，去掉或者调低 noImplicitAny 配置:
```
{
  "compilerOptions": {
    "noImplicitAny": false // 默认是 true,启用时会要求使用 import type
  }
}
```
2.修改ESLint，关闭该规则，在 .eslintrc 或者 package.json 的 ESLint 配置中,关闭该规则:
```
{
  "rules": {
    "import/prefer-default-export": "off"  
  } 
}
```

**Comment by zlmica** [comment]
> zerone api 生成的 ts 文件中对于类的导入使用了`import`，而不是`import type` ![image](https://user-images.githubusercontent.com/28662535/249102690-bab54ac6-b123-41dc-affe-a91fc4657e7d.png)
> 
> 期望自动生成`import type`

出现这个报错，有两种可能：
1.项目使用了 tsconfig.json 配置的 noImplicitAny: true, 一个没有。
当设置 noImplicitAny 时,TypeScript 会强制要求明确指定类型。而通过 import 而非 import type 导入时,默认会将类型设置为 any。所以一个项目会报错要求改为 import type。
2.项目使用了 ESLint 规则要求必须使用 import type。

可以尝试修改配置
1.修改 TypeScript 配置，修改 tsconfig.json，去掉或者调低 noImplicitAny 配置:
```
{
  "compilerOptions": {
    "noImplicitAny": false // 默认是 true,启用时会要求使用 import type
  }
}
```
2.修改ESLint，关闭该规则，在 .eslintrc 或者 package.json 的 ESLint 配置中,关闭该规则:
```
{
  "rules": {
    "import/prefer-default-export": "off"  
  } 
}
```
