### ISSUE TITLE
axios 实例问题

### ISSUE THREAD

**Issue by liyao52033** [zeronejs/zerone#734]
swagger.config.json里已经指定了"axiosInstanceUrl": "@/utils/request",为什么生成的接口里全是import request from "axios"，而不是import request from "@/utils/request"，这不根本没用到axios 实例嘛

**Comment by zlmica** [comment]
你好，如果项目 axios 实例路径为 @/utils/request，默认是不需要配置的，可以贴出来你的配置代码及问题代码

**Comment by zlmica** [comment]
> swagger

https://github.com/zeronejs/zerone/issues/734#issue-1827969201

**Comment by zlmica** [comment]
> swagger.config.json里已经指定了"axiosInstanceUrl": "@/utils/request",为什么生成的接口里全是import request from "axios"，而不是import request from "@/utils/request"，这不根本没用到axios 实例嘛

你好，如果 axios 实路径为 @/utils/request 默认是不需要配置的，可以贴出来代码截图看下问题

**Comment by liyao52033** [comment]
> > swagger.config.json里已经指定了"axiosInstanceUrl": "@/utils/request",为什么生成的接口里全是import request from "axios"，而不是import request from "@/utils/request"，这不根本没用到axios 实例嘛
> 
> 你好，如果 axios 实路径为 @/utils/request 默认是不需要配置的，可以贴出来代码截图看下问题

1. swagger.config.json配置
![00785362466801d6c32ea1c735bf79c](https://github.com/zeronejs/zerone/assets/68154076/07690150-9720-4d85-8e1f-f07daa9f7398)
2. axios实例路径及运行命令
![2bfa5cc9e9554f69a6a2afd79c94659](https://github.com/zeronejs/zerone/assets/68154076/11f7a85b-9308-4b7c-a4b8-194f8c84589f)
3. 生成的代码是import request from "axios"
![1829309922c1435018e6b3a11ae059a](https://github.com/zeronejs/zerone/assets/68154076/6f6af5de-844a-46c8-8ae3-baa8ad576a30)

**Comment by zzh948498** [comment]
> swagger.config.json里已经指定了"axiosInstanceUrl": "@/utils/request",为什么生成的接口里全是import request from "axios"，而不是import request from "@/utils/request"，这不根本没用到axios 实例嘛

请执行 zerone info，我看下node、zeronejs 以及系统版本

**Comment by zzh948498** [comment]
> swagger.config.json里已经指定了"axiosInstanceUrl": "@/utils/request",为什么生成的接口里全是import request from "axios"，而不是import request from "@/utils/request"，这不根本没用到axios 实例嘛

Windows系统 zerone api -js 生成实例错误问题已修复，请升级@zeronejs/cli 至最新版的2.12.0
