### ISSUE TITLE
没有对枚举类型参数进行处理

### ISSUE THREAD

**Issue by jqrrgmvtk** [zeronejs/zerone#772]
swagger接口文档生成TS代码，当控制器方法有枚举参数类型时，apiTypes目录生成对应的那个枚举类型文件里是空的。

**Comment by zzh948498** [comment]
> swagger接口文档生成TS代码，当控制器方法有枚举参数类型时，apiTypes目录生成对应的那个枚举类型文件里是空的。

请提供一个最小代码仓库，以复现这个问题。（docsUrl支持指定本地json文件）

**Comment by jqrrgmvtk** [comment]
![枚举没有生成TS类型](https://github.com/zeronejs/zerone/assets/24597643/1e321513-c798-4510-baac-eff68ea9b152)

[swagger.json](https://github.com/zeronejs/zerone/files/13633052/swagger.json)

**Comment by zzh948498** [comment]
> ![枚举没有生成TS类型](https://private-user-images.githubusercontent.com/24597643/289478311-1e321513-c798-4510-baac-eff68ea9b152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDk3NDgsIm5iZiI6MTcwMjM0OTQ0OCwicGF0aCI6Ii8yNDU5NzY0My8yODk0NzgzMTEtMWUzMjE1MTMtYzc5OC00NTEwLWJhYWMtZWZmNjhlYTliMTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyNTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzY2RjMTE4MDFiZjNiNDE5Y2YzNDE5MTU1MGVlNTJlN2IwZWQxMDFlZDUzNzMzYTE4MTliNTAzYjE5NWI2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tW5xzWOchmI2uRvaQ8tsRzWW3NGcy6TmJYrZrW66I4k)
> 
> [swagger.json](https://github.com/zeronejs/zerone/files/13633052/swagger.json)

请安装最新版
