### ISSUE TITLE
swagger.config.json 中的 prefix 不生效

### ISSUE THREAD

**Issue by One0neSix6** [zeronejs/zerone#773]
作者大大你好，`swagger.config.json` 中的 `prefix` 和我预想的不一样。我的理解是，假设「添加客户接口」的请求路径为「/customer/add」，在 `swagger.config.json` 中设置 prefix = "/api"，此时请求路径为「/api/customer/add」。但事实是这样生成的文件是空白的，而且文件名也会改变（postCustomerAdd 变为 postApiCustomerAdd），实际上根本不需要改变文件名。
例如：未加 `prefix` 配置。
  ```json
  {
    "docsUrl": "json文件地址",
    "axiosInstanceUrl": "axios",
  }
  ```
  postCustomerAdd.ts 文件
  ```typescript
  export function postCustomerAdd (input: postCustomerAddDto) {
      return request.post<DeepRequired<ResponseLong>>(`/customer/add`, input);
  }
  ```
填加 `prefix` 配置后：
  ```json
  {
    "docsUrl": "json文件地址",
    "axiosInstanceUrl": "axios",
    "prefix": "/api"
  }
  ```
  postCustomerAdd.ts 文件
  ```typescript
  export function postCustomerAdd (input: postCustomerAddDto) {
      return request.post<DeepRequired<ResponseLong>>(`/api/customer/add`, input);
  }
  ```

**Comment by zzh948498** [comment]
> 作者大大你好，`swagger.config.json` 中的 `prefix` 和我预想的不一样。我的理解是，假设「添加客户接口」的请求路径为「/customer/add」，在 `swagger.config.json` 中设置 prefix = "/api"，此时请求路径为「/api/customer/add」。但事实是这样生成的文件是空白的，而且文件名也会改变（postCustomerAdd 变为 postApiCustomerAdd），实际上根本不需要改变文件名。 例如：未加 `prefix` 配置。
> 
> ```json
> {
>   "docsUrl": "json文件地址",
>   "axiosInstanceUrl": "axios",
> }
> ```
> 
> postCustomerAdd.ts 文件
> 
> ```ts
> export function postCustomerAdd (input: postCustomerAddDto) {
>     return request.post<DeepRequired<ResponseLong>>(`/customer/add`, input);
> }
> ```
> 
> 填加 `prefix` 配置后：
> 
> ```json
> {
>   "docsUrl": "json文件地址",
>   "axiosInstanceUrl": "axios",
>   "prefix": "/api"
> }
> ```
> 
> postCustomerAdd.ts 文件
> 
> ```ts
> export function postCustomerAdd (input: postCustomerAddDto) {
>     return request.post<DeepRequired<ResponseLong>>(`/api/customer/add`, input);
> }
> ```

方法名是根据请求路由创建的，这样方法名是唯一的，在后端多服务场景下，用于区分多服务很有帮助。prefix 和axios创建实例的baseURL你可以根据情况使用，建议大部分场景都可以使用环境变量+baseUrl

**Comment by zzh948498** [comment]
方法名很重要的一个作用是见名知意，方法名加上prefix 之后，我就知道这个方法属于哪个服务啦
