### ISSUE TITLE
json链接读取失败 ！！！

### ISSUE THREAD

**Issue by zongyanglaobiao** [zeronejs/zerone#774]
{
  "docsUrl": "http://localhost:9101/v2/api-docs?group=snowy-web-app",
  "axiosInstanceUrl": "axios"
}
您好，以上是我的配置使用命令zerone api -js -p ./src/demo03_openapi/api/抛出json链接读取失败 ！！！这是什么问题，但是链接没有问题

**Comment by zzh948498** [comment]
> { "docsUrl": "http://localhost:9101/v2/api-docs?group=snowy-web-app", "axiosInstanceUrl": "axios" } 您好，以上是我的配置使用命令zerone api -js -p ./src/demo03_openapi/api/抛出json链接读取失败 ！！！这是什么问题，但是链接没有问题

可能的原因：
1. swagger仅支持3.0及以上
2. 确保你的链接是json文档，并非是swagger ui地址
3. 以上方法还不行，http://gen.api.noding.top/docs-json  使用我这个示例链接，并查看区别
