### ISSUE TITLE
文件创建失败

### ISSUE THREAD

**Issue by zongyanglaobiao** [zeronejs/zerone#776]
这个创建文件我本人觉得非常影响用户体验，如果文件夹不存在则报错其实是没必要的，直接就可以创建
[Error: ENOENT: no such file or directory, lstat 'D:\Program Files (x86)\idea\IDEAproject\github\Jay-FM\jay-fm-front-end\src\api\dist\controller'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'D:\\Program Files (x86)\\idea\\IDEAproject\\github\\Jay-FM\\jay-fm-front-end\\src\\api\\dist\\controller'
}

**Comment by zzh948498** [comment]
> 这个创建文件我本人觉得非常影响用户体验，如果文件夹不存在则报错其实是没必要的，直接就可以创建 [Error: ENOENT: no such file or directory, lstat 'D:\Program Files (x86)\idea\IDEAproject\github\Jay-FM\jay-fm-front-end\src\api\dist\controller'] { errno: -4058, code: 'ENOENT', syscall: 'lstat', path: 'D:\Program Files (x86)\idea\IDEAproject\github\Jay-FM\jay-fm-front-end\src\api\dist\controller' }

可以详细描述下你遇到的问题吗：
1. 在哪步出错的
2. 如何复现
3. 如果是生成接口时出错的，请提供最小json文件
