### ISSUE TITLE
建议给controller里接口函数设置返回值类型

### ISSUE THREAD

**Issue by 4379711** [zeronejs/zerone#777]
建议给controller里接口函数设置返回值类型

**Comment by 4379711** [comment]
cli工具,没有返回值类型很难受,很多情况下类型推断不好用

**Comment by zzh948498** [comment]
> cli工具,没有返回值类型很难受,很多情况下类型推断不好用

直接定义返回值类型吗，我这里目前没有这样的需求，类型推断可以满足我几乎所有需求
你可以把你的情况说下 ，我再考虑下

**Comment by 4379711** [comment]
其实也满足了我大部分场景的需求,如果可以选择性的添加返回值类型,那就更好了
