### ISSUE TITLE
你好支持anyof ？

### ISSUE THREAD

**Issue by dyyz1993** [zeronejs/zerone#778]
`"showIntro": {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "object"
                },
                {
                  "type": "string"
                }
              ]
            },
            "description": "演出介绍",
            "title": "演出介绍",
            "displayType": "text"
          }`

我使用anyof之后，输出的为unknow[]

**Comment by zzh948498** [comment]
> `"showIntro": { "type": "array", "items": { "anyOf": [ { "type": "object" }, { "type": "string" } ] }, "description": "演出介绍", "title": "演出介绍", "displayType": "text" }`
> 
> 我使用anyof之后，输出的为unknow[]

请安装3.4.0版本
