### ISSUE TITLE
Dto如果有枚举的时候就会生成不出来

### ISSUE THREAD

**Issue by RangzhiWu** [zeronejs/zerone#779]
"WorkflowInstanceStatusCountDto": {
                "type": "object",
                "properties": {
                    "state": {
                        "type": "string",
                        "enum": [
                            "WorkflowExecutionStatus{code=0, desc='submit success'}",
                            "WorkflowExecutionStatus{code=1, desc='running'}",
                            "WorkflowExecutionStatus{code=2, desc='ready pause'}",
                            "WorkflowExecutionStatus{code=3, desc='pause'}",
                            "WorkflowExecutionStatus{code=4, desc='ready stop'}",
                            "WorkflowExecutionStatus{code=5, desc='stop'}",
                            "WorkflowExecutionStatus{code=6, desc='failure'}",
                            "WorkflowExecutionStatus{code=7, desc='success'}",
                            "WorkflowExecutionStatus{code=12, desc='delay execution'}",
                            "WorkflowExecutionStatus{code=14, desc='serial wait'}",
                            "WorkflowExecutionStatus{code=15, desc='ready block'}",
                            "WorkflowExecutionStatus{code=16, desc='block'}",
                            "WorkflowExecutionStatus{code=17, desc='wait to run'}"
                        ]
                    },
                    "count": {
                        "type": "integer",
                        "format": "int32"
                    }
                }
            },

**Comment by zzh948498** [comment]
> ```
>         "WorkflowInstanceStatusCountDto": {
>             "type": "object",
>             "properties": {
>                 "state": {
>                     "type": "string",
>                     "enum": [
>                         "WorkflowExecutionStatus{code=0, desc='submit success'}",
>                         "WorkflowExecutionStatus{code=1, desc='running'}",
>                         "WorkflowExecutionStatus{code=2, desc='ready pause'}",
>                         "WorkflowExecutionStatus{code=3, desc='pause'}",
>                         "WorkflowExecutionStatus{code=4, desc='ready stop'}",
>                         "WorkflowExecutionStatus{code=5, desc='stop'}",
>                         "WorkflowExecutionStatus{code=6, desc='failure'}",
>                         "WorkflowExecutionStatus{code=7, desc='success'}",
>                         "WorkflowExecutionStatus{code=12, desc='delay execution'}",
>                         "WorkflowExecutionStatus{code=14, desc='serial wait'}",
>                         "WorkflowExecutionStatus{code=15, desc='ready block'}",
>                         "WorkflowExecutionStatus{code=16, desc='block'}",
>                         "WorkflowExecutionStatus{code=17, desc='wait to run'}"
>                     ]
>                 },
>                 "count": {
>                     "type": "integer",
>                     "format": "int32"
>                 }
>             }
>         },
> ```

在你提供的 enum 部分，枚举值的格式看起来不像是典型的简单字符串集合。在标准的OpenAPI规范中，枚举通常只包含简单的字符串或数字，而不是带有描述性信息的复杂对象。标准的OpenAPI枚举应该如下所示（以字符串为例）：
